export enum EQuestTypes {
  SEND_ERC20 = 'SEND_ERC20',
  RECEIVE_ERC20 = 'RECEIVE_ERC20',
  SEND_NFT = 'SEND_NFT',
  RECEIVE_NFT = 'RECEIVE_NFT',
}

export enum EQuestStatuses {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CLAIM = 'CLAIM',
}
